### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by itplayer** [rulebook-rules/rulebook#53]
Is RuleBook thread safe for multithreading environment?
Should I create an instance for each thread for rule evaluation?

**Comment by Clayton7510** [comment]
If you are referring to creating an instance per RuleBook, then yes, you should have different instances per thread. If you are using Spring, then the RuleBookFactoryBean will do that for you.

**Comment by Clayton7510** [comment]
So, I think what I will do (what I have started doing) for thread safety is add an invoke(facts) method to Rule. So that facts can hold state outside of the Rule. That way, different groups of facts can be given to any given Rule without worrying about the state of the Rule. Then I will have the RuleBook (CoRRuleBook) chain rules using the externally supplied facts only instead of the internal facts state of each Rule (which right now, is just overwritten on subsequent runs). That should make RuleBooks and their Rules threadsafe, so long as you use different [instances of] facts for different threads.

The interesting thing comes with the POJO rules. Since POJO rules map state to POJOs, the execution of the rule chain would have to be locked. In that case, there will be a performance penalty. So, I think I will just allow the developer to decide with a threadsafe option in RuleBookRunner that can be passed into the constructor. If you need it to be threadsafe, create a RuleBookRunner that's marked as threadsafe and take the performance hit. If you don't need it to be threadsafe, don't mark it as such and it runs the way it always did. 

Spring support also leverages RuleBookRunner. So, that would work the same way.

Anyway, those are my thoughts right now.

**Comment by Clayton7510** [comment]
So, I have thread safety available in non-POJO RuleBooks in the ThreadSafety branch. If you create a RuleBook, running the same instance in different threads with different facts should cause no issues since facts are no longer persisted in the rules. 

However, with POJO Rulebooks, facts do hold state - such is the nature of objects and how they are adapted to rules. So, I now give you a choice in the RuleBookRunner: (1) completely thread safe or (2) not thread safe. The completely thread safe option synchronizes the execution of the RuleBookRunner. The not thread safe option makes it the responsibility of the developer to ensure the same instance of a RuleBookRunner isn't being run in different threads at the same time. This choice is available via a new RuleBookRunner constructor argument and also in the configuration of the RuleBookFactoryBean for Spring.

The tradeoff is therefore, simplicity over flexibility. In the future, this tradeoff may become less. But for now, I think the simplest way without breaking existing interfaces is this approach. Of course, other recommendations are always welcome.

**Comment by Clayton7510** [comment]
What fun is taking the easy way out? :-)
Block synchronization on the running of a RuleBook seems kind of expensive. So, I am now looking into more of a copy on run type of functionality. Basically, every time a thread safe RuleBookRunner is run, it creates a new instance of RuleBookRunner and therefore, new instances of its POJO Rules. The only gotcha I am running into is the Result, which I suppose will have to store a Result per thread.

**Comment by Clayton7510** [comment]
I haven't been able to spend as much time working on this as I would like. But I expect this issue to be resolved shortly. After resolving thread safety concerns in all but POJO RuleBooks, I decided to create an immutable RuleBookRunnerFactory class that literally just creates new instances of RuleBookRunners.

How does this resolve thread safety in POJO RuleBooks? It doesn't. But what it does do allow each thread to run a separate instance of a POJO RuleBook. Since POJO RuleBook's must maintain state, I really don't want to be running the same POJO RuleBook across multiple threads. But I do want an easy way to grab a new instance for each execution. This allows that to happen and it allows it work with Spring too.

The only piece left to fix is how Result objects are handled. And since that is already abstracted, I can just maintain the Result on a per thread basis unobtrusively... at least until I introduce multi-threaded rulebooks, which will likely happen sometime later this year.

**Comment by Clayton7510** [comment]
I just pushed some work I had queued from last night. Thread Safety branch should be there. I will push the 0.7 snapshot this evening.

**Comment by wheezymustafa** [comment]
So just to clarify - You're saying new instances per thread should be enough to avoid any issues, or is there something underneath which needs to be addressed before using this in a multi threaded app?

**Comment by igorky** [comment]
wheezymustafa, I faced with race condition issues in 6.2.0 and new instances per thread doesn't fix the problem. So you have to wait till next release.

**Comment by Clayton7510** [comment]
Different instances of RuleBooks per thread are currently needed prior to v0.7, which is nearly done - although some updates will be added. The 0.7 Snapshot is in Maven Central.

To be clear, if you reuse the same Facts across RuleBooks, even if you have different instances per thread, there will be impacts across any threads that use the same facts. This is being looked into for v0.7 too. So, it's worth a look now. But it's not yet  in it's final state.

**Comment by Clayton7510** [comment]
In terms of release timeframe for v0.7:

Things have been a little hairy lately.  But this issue is next on deck. Est. release date is between 1-4weeks.

**Comment by igorky** [comment]
Thank you Clayton7510 for the information.
In my case I used a new instance of RuleBook and new facts per thread and I still faced with race conditions in run method.

**Comment by Clayton7510** [comment]
@igorky Hmm... I'm not entirely sure how that could happen. Would you mind posting the code you used or an example where you saw this issue?

**Comment by Clayton7510** [comment]
0.7-SNAPSHOT has been updated and and tested with POJO rules and RuleBooks with different Results across different threads. There are a couple more concurrent tests that will be added. But it's pretty much where it's going to be. 

One thing you still have to be aware of is shared facts (and FactMaps). Using the same facts across the same the RuleBook run in different threads or different RuleBooks can have two different RuleBook executions changing state on the same facts. But if you use different facts, RuleBooks (and Rules) no longer maintain state. Results are also now internally segmented per thread for thread safety - how you interact with them is the same, but they can now support the same RuleBook running in different threads with different facts at the same time as of v0.7-SNAPSHOT.

**Comment by Clayton7510** [comment]
v0.7 was released with updates for thread safety.
