### ISSUE TITLE
When-condition of rule is not accessed

### ISSUE THREAD

**Issue by Gersee** [rulebook-rules/rulebook#54]
Hi,

I'm trying to use RuleBook version 0.5 in my Spring-application. It seems like the _when_-part will **never** be evaluated, so I access for each rule the _then_-part. 
First there comes my code, then the issue is explained with a little bit more details.

## The Code:
My Pom contains:

    <dependency>
	    <groupId>com.deliveredtechnologies</groupId>
	    <artifactId>rulebook-core</artifactId>
	    <version>0.5</version>
	</dependency>
  	<dependency>
	    <groupId>com.deliveredtechnologies</groupId>
	    <artifactId>rulebook-spring</artifactId>
	    <version>0.5</version>
	</dependency>

Like in the wiki/readme told I created a @Configuration-bean:

    @Configuration
    public class RuleBookSpringConfig {
	  @Bean
	  public RuleBookFactoryBean ruleBook() throws InvalidClassException {
		return new RuleBookFactoryBean("my.package.rulebook.myRules"); 
	  }
    }

I defined one rule in the package:

    @Rule(order =1)
    public class MyRule {
	  public MyRule() {}
	
      @Given("field")
	  private myClass field;
	  
	  @When
	  public boolean when() {
		System.out.println("Evaluate condition");
		return field.isPropertySet(); 
	  }
	  
	  @Then
	  public RuleState then() {
		System.out.println("Rule is correct");
		return RuleState.NEXT;
	  }
    }

This rule is used here:

    NameValueReferableMap<FieldMetaElement> facts = new FactMap<>();
    facts.setValue("field", instanceOfMyClass);
    this.ruleBook.run(facts);

## The issue:
If I run the code, my output is every time `Rule is correct`, wether the property is set or not. The output `Evaluate condition` is never displayed. So I changed the when-part to:

    @When
    public boolean when() {
        return false;
    }

The output is every time `Rule is correct` again. If I set a breakpoint to `when()` it does not stop there. So the _when_-part is not executed at every time. 
If I set a breakpoint at `com.deliveredtechnologies.rulebook.model.runner.RuleAdapter.class` line 126 - `public Predicate<NameValueReferableMap> getCondition()` the application does not stop there. Same at `com.deliveredtechnologies.rulebook.runner.RuleAdapter.class` line 121 - `public Predicate getWhen()`.
I tried to use a manually instance of RuleBook without spring and have exactly the same situation.
Same situation comes if I use a rule with a Result or more rules.

## Additional information:
The imports at the rule-class are:

- import com.deliveredtechnologies.rulebook.RuleState;
- import com.deliveredtechnologies.rulebook.annotation.Given;
- import com.deliveredtechnologies.rulebook.annotation.Rule;
- import com.deliveredtechnologies.rulebook.annotation.Then;
- import com.deliveredtechnologies.rulebook.annotation.When;

The imports at the rule-usage-class are:

- import com.deliveredtechnologies.rulebook.FactMap;
- import com.deliveredtechnologies.rulebook.NameValueReferableMap;
- import com.deliveredtechnologies.rulebook.model.RuleBook;
- import com.deliveredtechnologies.rulebook.Result;

The import at Spring-configuration is:

- import com.deliveredtechnologies.rulebook.spring.RuleBookFactoryBean;

**Comment by Clayton7510** [comment]
@Gersee I haven't forgot about you. I just have to prep for a meeting with a client tomorrow.
So, I will check this out and respond later tomorrow.

**Comment by Clayton7510** [comment]
@Gersee you are correct. I checked out your example and there is a situation where the @When condition is not evaluated. I corrected this bug and updated it in the 0.5.1-SNAPSHOT and on the develop branch. I will be doing a patch release to push 0.5.1 to Maven Central this weekend.

**Comment by Clayton7510** [comment]
I updated the tests and just pushed 0.5.1 to Maven with this bug fix.

**Comment by agnibha92** [comment]
Still Facing The Same issue in 0.11. I am currently using POJO Based Rules and the runner skipped the method marked with @When annotation and Directly Called @Then

**Comment by agnibha92** [comment]
```
_rule.setCondition(Arrays.stream(_pojoRule.getClass().getMethods())
            .filter(method -> method.getReturnType() == boolean.class || method.getReturnType() == Boolean.class)
            .filter(method -> 
Arrays.stream(method.getDeclaredAnnotations()).anyMatch(When.class::isInstance))
            .findFirst()
            .<Predicate>map(method -> object -> {
              try {
                return (Boolean) method.invoke(_pojoRule);
              } catch (InvocationTargetException | IllegalAccessException ex) {
                if (_actionType == RuleChainActionType.ERROR_ON_FAILURE) {
                  throw new RuleException(ex.getCause() == null ? ex : ex.getCause());
                }
                LOGGER.error(
                    "Unable to validate condition due to an exception. It will be evaluated as false", ex);
                return false;
              }
            })
            //If the condition still can't be determined, then just hand back one that returns true
            .orElse(o -> true));
```

This code is returning no methods.

**Comment by agnibha92** [comment]
I Used The When Method as a private method, because of that the problem arrived as `getMethods()` returns only public method. Is there any reason why `getDeclaredMethods()` was not used?
